apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: notes-api
  template:
    metadata:
      labels:
        component: notes-api
    spec:
      containers:
      - name: notes-api
        image: fhsinchy/notes-api
        resources:
          limits:
            memory: "64Mi"
            cpu: "125m"
        ports:
        - containerPort: 3000
        env:
        - name: DB_CONNECTION
          value: pg
